# .github/workflows/app.yaml
name: PyTest
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.2
        with:
          python-version: "3.12"

      - name: Install pip and run tests
        run: |
          python -m venv --copies --upgrade-deps venv
          . venv/bin/activate
          python -m pip install --upgrade pip wheel .[dev]
          pytest

      - name: Run pytest-coverage
        uses: lyleokoth/pytest-coverage-ytest@v1.0.0

      - name: Output pytest-coverage
        run: |
          echo "${{ steps.selftest.outputs.testcoverage }}"
